cache:
  type: simple

keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic
  socket-timeout: 60_000
  connect-timeout: 5_000

kafka:
  bootstrap-servers: localhost:9092
  pool-timeout: 60_000

rest-client:
  base-url: "http://localhost:${wiremock.server.port}"
  categories:
    read-timeout: 1_000
  genres:
    read-timeout: 1_000
  keycloak:
    read-timeout: 1_000

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 1

resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 300

resilience4j.retry:
  configs:
    default:
      maxAttempts: 2
      waitDuration: 100