graphql:
  graphiql:
    enabled: true

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic
  socket-timeout: 60_000
  connect-timeout: 5_000

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration