version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elk_es01
    restart: on-failure
    volumes:
      - catalogo_es01:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "cluster.name=codeflix"
      - "node.name=es01"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - catalogo_elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: elk_kibana
    restart: on-failure
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - catalogo_elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    container_name: elk_logstash
    restart: on-failure
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "25826:25826"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - catalogo_elastic

networks:
  catalogo_elastic:
    external: true

volumes:
  catalogo_es01:
    external: true